version: 2.1

executors:
  docker_hugo_node:
    docker:
      - image: node:10-alpine

jobs:
  build:
    executor: docker_hugo_node
    environment:
        - HUGO_VERSION: '0.58.3'
        - HUGO_BINARY: hugo_0.58.3_linux-64bit
        - GLIBC_VERSION: 2.28-r0
    steps:
      - run:
          command: |
            apk update
            apk add bash git wget ca-certificates autoconf automake build-base

            rm -rf /var/cache/apk/*
            mkdir /usr/local/hugo
            wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY}.tar.gz -O /usr/local/hugo/${HUGO_BINARY}.tar.gz
            tar xzf /usr/local/hugo/${HUGO_BINARY}.tar.gz -C /usr/local/hugo/
            ln -s /usr/local/hugo/hugo /usr/local/bin/hugo
            rm /usr/local/hugo/${HUGO_BINARY}.tar.gz
            rm -rf /tmp/* /var/cache/apk/*

      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          command: |
            export CONTEXT="production"
            yarn
            chmod +x deploy.sh
            ./deploy.sh

      - persist_to_workspace:
          root: '~'
          paths:
            - project/

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  test:
      executor: docker_hugo_node
      environment:
        - HUGO_VERSION: '0.58.3'
        - HUGO_BINARY: hugo_0.58.3_linux-64bit
        - GLIBC_VERSION: 2.28-r0
      steps:
        - run:
            command: |
              apk update
              apk add bash git wget ca-certificates autoconf automake build-base

              rm -rf /var/cache/apk/*
              mkdir /usr/local/hugo
              wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY}.tar.gz -O /usr/local/hugo/${HUGO_BINARY}.tar.gz
              tar xzf /usr/local/hugo/${HUGO_BINARY}.tar.gz -C /usr/local/hugo/
              ln -s /usr/local/hugo/hugo /usr/local/bin/hugo
              rm /usr/local/hugo/${HUGO_BINARY}.tar.gz
              rm -rf /tmp/* /var/cache/apk/*

              # Needed for BrowserStackLocal, see https://github.com/browserstack/browserstack-local-nodejs/issues/32, https://github.com/browserstack/browserstack-local-nodejs/issues/20 and https://github.com/sgerrand/alpine-pkg-glibc
              wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
              wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk
              apk add glibc-${GLIBC_VERSION}.apk glibc-bin-${GLIBC_VERSION}.apk

        - attach_workspace:
            at: ~/

        - run:
            command: |
              hugo server --baseURL "http://localhost" --disableFastRender --minify > /dev/null &
              yarn test

        - store_artifacts:
            path: test/reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
              - build
